### PR TITLE
Default `outputStyle` to `compressed` in release mode

### PR DESCRIPTION
**Pull request by leonsenft**

### CODE REVIEW

**Comment by nshahan** [comment]
Good idea. Could you add a CHANGELOG entry for another dot release?

**Comment by leonsenft** [comment]
Of course! Would you like me to bump the pubspec and everything else necessary for release? Or just the CHANGELOG entry?

Edit: I did both, let me know if you'd prefer to hold off until more changes are in for a release.

**Comment by nshahan** [comment]
AFAIK No other changes planned in the near future. I'll merge and publish.

**Comment by leonsenft** [comment]
Thanks!

**Pull request merged**
