### PR TITLE
Add 1.1.2 to changelog, edit nits and style

### PR DESCRIPTION
**Pull request by 4cm4k1**
@kevmoo You merged my PR just as I pushed this commit. 😆

### CODE REVIEW

**Comment by kevmoo** [comment]
Gah! Sorry.

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
@4cm4k1 – let me know if you need merging 😄

**Comment by 4cm4k1** [comment]
Should be all good now. :smile:

**Comment by kevmoo** [comment]
meaning I should merge?

**Comment by 4cm4k1** [comment]
Yes, sorry! Haha.

**Comment by kevmoo** [comment]
Thanks!

**Pull request merged**
