### PR TITLE
Fix typo in CHANGELOG.md filename

### PR DESCRIPTION
**Pull request by 4cm4k1**
This will make it show up properly on the Pub website at https://pub.dartlang.org/packages/sass_builder#-changelog-tab-. 😄

### CODE REVIEW

**Comment by kevmoo** [comment]
With content would be nice. 😄 

You could at least cover the last published release...

**Comment by kevmoo** [comment]
An empty changelog is worse than no changelog, IMHO

**Comment by 4cm4k1** [comment]
@kevmoo Don't you see this?

## 1.1.1

- Fixed compatibility with `.sass` file compilation.
- Bump `sass` dependency to ^1.0.0-beta.4.

## 1.1.0

- Support the latest version of `package:build_runner`.
- Align the logger name with the package name: `sass_builder`.
- upgrade to `build` to `^0.11.1`

## 1.0.1

- Support the latest version of `package:build_runner`.
- Align the logger name with the package name: `sass_builder`.
- upgrade to `build` to `^0.10.2+1`

## 1.0.0

- write assets to temporary directory

## 0.2.0

- upgrade `build_runner` to version `^0.4.0`

## 0.1.2

- fix #2  Keep trying to build removed scss

## 0.1.1

- add missing import

## 0.1.0

- upgrade build to `^0.9.1` and build_runner to `^0.3.2`

## 0.0.2

- recompile main files after editing sub files

## 0.0.1

first version

**Comment by kevmoo** [comment]
Ah! The rename showed up empty - weird.

Having the correct name is goodness :-)

**Review by kevmoo — APPROVED** [review]

**Pull request merged**
