### PR TITLE
Fix crash with 'Logger' class.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/dart-league/sass_builder/issues/30.

/cc @kevmoo @nshahan @luisvt

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]

**Comment by matanlurey** [comment]
@kevmoo Are you able to merge/publish?

**Comment by kevmoo** [comment]
In theory, yes – wanted to wait on @nshahan. I have very little context here...

...unless it's crazy urgent

**Comment by matanlurey** [comment]
Not _crazy_ urgent. Context is here: https://github.com/dart-lang/build/issues/1181.

tl;dr everyone that uses `sass_builder` (even transitively) is broken right now.

**Comment by indiealexh** [comment]
There is a working work around, so not super urgent. Just annoying.

**Comment by juarezpaf** [comment]
@indiealexh would you mind to share the current working workaround? I've just tried to run a fresh newly created AngularDart project via WebStorm and it failed.

**Comment by indiealexh** [comment]
@juarezpaf please see the stack over flow link in #30

**Comment by nshahan** [comment]
LGTM but would it be better to just start using the logger exported by the build package?
https://github.com/dart-lang/build/blob/master/build/lib/build.dart#L12

**Comment by matanlurey** [comment]
@nshahan Probably, but I rather not tom-fool it around with it in this priority fix.

**Review by luisvt — APPROVED** [review]

**Comment by matanlurey** [comment]
Can someone land/publish this?

**Comment by nshahan** [comment]
Done.

**Pull request merged**
